/* ============================================================
   Doppy — Signup (dueños)
   ------------------------------------------------------------
   FIX 1: el script de Supabase ahora se carga desde la ruta UMD
   explícita en el HTML (…/dist/umd/supabase.min.js). La versión
   genérica (…/@supabase/supabase-js sin la ruta) no siempre deja
   `window.supabase` disponible en el navegador, y por eso a veces
   no cargaba nada (mismo bug que tuvo dashboardda.html).

   FIX 2: se sacó la lógica que "adivinaba" el nombre de la tabla
   de usuarios probando clients/client/clientes/usuarios/users/
   owners/perfiles/profiles hasta que alguna no tirara error. La
   tabla real siempre fue "users" — esa adivinanza era innecesaria
   y arriesgada (podía "acertar" con una tabla que no correspondía).

   FIX 3: el insert ahora usa las columnas reales de "users"
   (name, email, auth_user_id) en vez de una tabla y columnas que
   no existen.
   ============================================================ */

const supabaseClient = window.supabase.createClient(
  'https://xyiebwrjkmvmcpdhenjk.supabase.co',
  'sb_publishable_0Qsrr-I39mcgsm_yj8dEEA_DhtV_2fg'
);

function togglePass(id, btn) {
  const input = document.getElementById(id);
  const isText = input.type === 'text';
  input.type = isText ? 'password' : 'text';
  btn.style.color = isText ? 'var(--text-light)' : 'var(--blue)';
}

function showToast(msg) {
  const t = document.getElementById('toast');
  t.textContent = msg;
  t.classList.add('show');
  setTimeout(() => t.classList.remove('show'), 3000);
}

async function register() {
  const nombre = document.getElementById('nombre').value.trim();
  const email  = document.getElementById('email').value.trim();
  const pass   = document.getElementById('pass').value;
  const pass2  = document.getElementById('pass2').value;

  const btn = document.querySelector('.btn-cta');

  if (!nombre || !email || !pass || !pass2) {
    showToast('⚠️ Please fill in all fields.');
    return;
  }
  if (pass !== pass2) {
    showToast('⚠️ Passwords do not match.');
    return;
  }
  if (pass.length < 6) {
    showToast('⚠️ Password must be at least 6 characters long.');
    return;
  }
  if (!email.includes('@')) {
    showToast('⚠️ Enter a valid email address.');
    return;
  }

  btn.disabled = true;
  btn.textContent = 'Creating account…';

  try {
    // 1. Create the user in Supabase Auth. Supabase Auth stores the
    // password securely (hashed) itself — that's why we never save a
    // "contra"/password column anywhere in our own tables.
    const { data, error: authError } = await supabaseClient.auth.signUp({
      email: email,
      password: pass,
      options: {
        data: { nombre: nombre }
      }
    });

    if (authError) {
      console.error('[Doppy][Supabase] Auth error:', authError);
      showToast('❌ Error: ' + authError.message);
      return;
    }

    // If email confirmation is required, Supabase may not return a user id here.
    if (!data.user) {
      console.warn('[Doppy] Signup returned no user (email confirmation may be required).');
      showToast('⚠️ Check your email to confirm your account.');
      return;
    }

    // 2. Create the matching profile row in "users".
    // id_client is auto-generated by the database — never set it manually.
    const authUserId = data.user.id;
    const { error: dbError } = await supabaseClient
      .from('users')
      .insert([{
        name: nombre,
        email: email,
        auth_user_id: authUserId
      }]);

    if (dbError) {
      console.error('[Doppy][Supabase] Error saving profile:', dbError);
      showToast('⚠️ Account created but failed to save profile: ' + dbError.message);
      return;
    }

    showToast('🐾 Account created successfully!');
    document.getElementById('nombre').value = '';
    document.getElementById('email').value  = '';
    document.getElementById('pass').value   = '';
    document.getElementById('pass2').value  = '';

    setTimeout(() => {
      window.location.href = 'selpetdu.html';
    }, 800);

  } catch (err) {
    console.error('[Doppy] Unexpected error:', err);
    showToast('❌ An unexpected error occurred.');
  } finally {
    btn.disabled = false;
    btn.textContent = 'Sign up';
  }
}